In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('globalterrorismdb_0522dist.csv')
df.head()

/opt/homebrew/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (4,31,33,54,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [8]:
df.isna().sum().sort_values(ascending=False).head(15)

gsubname3           209683
weapsubtype4        209636
weapsubtype4_txt    209636
weaptype4           209633
weaptype4_txt       209633
claimmode3          209566
claimmode3_txt      209566
gsubname2           209522
divert              209368
claim3              209297
guncertain3         209296
gname3              209292
ransomnote          209131
attacktype3         209048
attacktype3_txt     209048
dtype: int64

In [15]:
def clean_gt_df(df, level):
    cols_to_drop = []
    for col in list(df.columns):
        if df[col].isna().sum() > level:
            cols_to_drop.append(col)
    df = df.drop(columns = cols_to_drop)
    print(cols_to_drop)
    return df

In [16]:
fiveKNulls = clean_gt_df(df, 5000)
fiveKNulls

['approxdate', 'resolution', 'location', 'summary', 'alternative', 'alternative_txt', 'attacktype2', 'attacktype2_txt', 'attacktype3', 'attacktype3_txt', 'targsubtype1', 'targsubtype1_txt', 'corp1', 'targtype2', 'targtype2_txt', 'targsubtype2', 'targsubtype2_txt', 'corp2', 'target2', 'natlty2', 'natlty2_txt', 'targtype3', 'targtype3_txt', 'targsubtype3', 'targsubtype3_txt', 'corp3', 'target3', 'natlty3', 'natlty3_txt', 'gsubname', 'gname2', 'gsubname2', 'gname3', 'gsubname3', 'motive', 'guncertain2', 'guncertain3', 'nperps', 'nperpcap', 'claimed', 'claimmode', 'claimmode_txt', 'claim2', 'claimmode2', 'claimmode2_txt', 'claim3', 'claimmode3', 'claimmode3_txt', 'compclaim', 'weapsubtype1', 'weapsubtype1_txt', 'weaptype2', 'weaptype2_txt', 'weapsubtype2', 'weapsubtype2_txt', 'weaptype3', 'weaptype3_txt', 'weapsubtype3', 'weapsubtype3_txt', 'weaptype4', 'weaptype4_txt', 'weapsubtype4', 'weapsubtype4_txt', 'weapdetail', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus', 'nwoundte', 'propextent', 'propextent_txt', 'propvalue', 'propcomment', 'nhostkid', 'nhostkidus', 'nhours', 'ndays', 'divert', 'kidhijcountry', 'ransom', 'ransomamt', 'ransomamtus', 'ransompaid', 'ransompaidus', 'ransomnote', 'hostkidoutcome', 'hostkidoutcome_txt', 'nreleased', 'addnotes', 'scite1', 'scite2', 'scite3', 'related']

,eventid,iyear,imonth,iday,extended,country,country_txt,region,region_txt,provstate,...,individual,weaptype1,weaptype1_txt,property,ishostkid,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,197000000001,1970,7,2,0,58,Dominican Republic,2,Central America & Caribbean,National,...,0,13,Unknown,0,0.0,PGIS,0,0,0,0
1,197000000002,1970,0,0,0,130,Mexico,1,North America,Federal,...,0,13,Unknown,0,1.0,PGIS,0,1,1,1
2,197001000001,1970,1,0,0,160,Philippines,5,Southeast Asia,Tarlac,...,0,13,Unknown,0,0.0,PGIS,-9,-9,1,1
3,197001000002,1970,1,0,0,78,Greece,8,Western Europe,Attica,...,0,6,Explosives,1,0.0,PGIS,-9,-9,1,1
4,197001000003,1970,1,0,0,101,Japan,4,East Asia,Fukouka,...,0,8,Incendiary,1,0.0,PGIS,-9,-9,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209701,202012310015,2020,12,31,0,228,Yemen,10,Middle East & North Africa,Al Hudaydah,...,0,6,Explosives,1,0.0,START Primary Collection,0,0,0,0
209702,202012310016,2020,12,31,0,228,Yemen,10,Middle East & North Africa,Al Hudaydah,...,0,6,Explosives,0,0.0,START Primary Collection,0,0,0,0
209703,202012310017,2020,12,31,0,75,Germany,8,Western Europe,Lower Saxony,...,0,8,Incendiary,1,0.0,START Primary Collection,-9,-9,0,-9
209704,202012310018,2020,12,31,0,4,Afghanistan,6,South Asia,Kabul,...,0,5,Firearms,0,0.0,START Primary Collection,-9,-9,0,-9
209705,202012310019,2020,12,31,1,33,Burkina Faso,11,Sub-Saharan Africa,Sahel,...,0,5,Firearms,0,-9.0,START Primary Collection,-9,-9,0,-9

In [13]:
fiveKNulls.isna().sum().sort_values(ascending=False)

longitude          4692
latitude           4691
natlty1            2014
natlty1_txt        2014
target1             635
city                426
guncertain1         380
ishostkid           178
specificity           1
multiple              1
targtype1_txt         0
gname                 0
individual            0
eventid               0
attacktype1_txt       0
weaptype1             0
weaptype1_txt         0
property              0
dbsource              0
INT_LOG               0
INT_IDEO              0
INT_MISC              0
targtype1             0
success               0
attacktype1           0
region_txt            0
imonth                0
iday                  0
extended              0
country               0
country_txt           0
region                0
provstate             0
suicide               0
vicinity              0
crit1                 0
crit2                 0
crit3                 0
doubtterr             0
iyear                 0
INT_ANY               0
dtype: int64

In [17]:
len(fiveKNulls)

209706

In [18]:
# drop null rows at this point
fiveKNulls = fiveKNulls.dropna()
len(fiveKNulls)

201569

In [20]:
fiveKNulls.isna().sum().head(2)

eventid    0
iyear      0
dtype: int64

In [21]:
fiveKNulls.to_csv('gtd_no_nulls.csv')